import { Text, View } from '@react-pdf/renderer'
import { styles } from '../theme'

/** The black header band shared by all three documents. */
export function DocHeader({ kind }: { kind: string }) {
  return (
    <View style={styles.header}>
      <View style={styles.headerBrand}>
        <Text style={styles.headerMark}>B2</Text>
        <Text style={styles.headerName}>Back2Basics</Text>
      </View>
      <Text style={styles.headerKind}>{kind.toUpperCase()}</Text>
    </View>
  )
}

/** A label/value row. `last` drops the hairline so a block doesn't end on a rule. */
export function Row({
  label,
  value,
  last = false,
}: {
  label: string
  value: string
  last?: boolean
}) {
  return (
    <View style={last ? styles.rowLast : styles.row}>
      <Text style={styles.label}>{label}</Text>
      <Text style={styles.value}>{value}</Text>
    </View>
  )
}

export function DocFooter({ note }: { note: string }) {
  return (
    <Text
      style={styles.footer}
      // Rendered on every page rather than only the first — a two-page invoice
      // whose second sheet carries no attribution is a loose sheet of paper.
      fixed
    >
      {note}
      {'\n'}
      Generated by the Back2Basics recovery platform. This document is
      system-generated and valid without a signature.
    </Text>
  )
}
